apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-test-ing
  # annotations:
  #   nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api
        host: todo2.natapat.me
        pathType: Prefix
        backend:
          service:
            name: backend-srv
            port:
              number: 5050
      - path: /swagger
        host: todo2.natapat.me
        pathType: Prefix
        backend:
          service:
            name: backend-srv
            port:
              number: 5050
      - path: /
        host: todo2.natapat.me
        pathType: Prefix
        backend:
          service:
            name: frontend-srv
            port:
              number: 80
            
  